# A small config for testing (Nested format)
model:
  block_size: 256 # context of up to 256 previous characters
  n_layer: 6
  n_head: 6
  n_embd: 384
  dropout: 0.2

training:
  output_dir: 'training/checkpoints'
  eval_interval: 250
  batch_size: 64
  learning_rate: 0.001
  max_steps: 1
  lr_decay_iters: 5000
  min_lr: 0.0001
  beta1: 0.9
  beta2: 0.99
  warmup_iters: 100
  weight_decay: 0.1
  decay_lr: true
  grad_clip: 1.0

data:
  path: 'dataset/processed/train.txt'

inference:
  temperature: 1.0
  top_p: 0.9
